-- 코드를 작성해주세요
WITH FISH AS (
    SELECT ID, I.FISH_TYPE, LENGTH, TIME, N.FISH_NAME
    FROM FISH_INFO I
    LEFT JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
)
SELECT COUNT(CASE WHEN FISH_NAME = 'BASS' OR FISH_NAME = "SNAPPER" THEN 1
END) AS FISH_COUNT
FROM FISH;